version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      terraform-all:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform/cluster"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      terraform-all:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/terraform/hetzner_server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "terraform"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      terraform-all:
        patterns:
          - "*"
