apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-${index}:9090
    isDefault: false
    editable: false

  - name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-query-${index}:10904
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-${index}:3100
    isDefault: false
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo-${index}:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus 