server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /var/promtail-positions/positions.yaml

clients:
  - url: http://loki-${index}:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.log

  - job_name: docker_log_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

  - job_name: auditd
    static_configs:
      - targets:
          - localhost
        labels:
          job: auditd
          __path__: /var/log/audit/audit.log  # Path to auditd logs
    pipeline_stages:
      - regex:
          expression: "type=(?P<type>[A-Z_]+).*pid=(?P<pid>[0-9]+).*uid=(?P<uid>[0-9]+).*"
      - labels:
          type:  # Extracted event type
          pid:   # Process ID
          uid:   # User ID
      - timestamp:
          source: time
          format: Unix  # Adjust if your logs have a different timestamp format 