server:
  http_listen_port: 3200

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_id: ${ip}
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4417"
        http:
          endpoint: "0.0.0.0:4418"

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m
  lifecycler:
    id: ${ip}
    ring:
      kvstore:
        store: memberlist

compactor:
  ring:
    instance_addr: ${ip}
    instance_id: tempo-${node_id}
    kvstore:
      store: memberlist
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: s3
    s3:
      bucket: ${bucket}
      endpoint: ${endpoint}
      access_key: ${access_key}
      secret_key: ${secret_key}
      region: ${region}
      insecure: false
      prefix: "tempo/"
    wal:
      path: /tmp/tempo/wal
      v2_encoding: snappy

metrics_generator:
  ring:
    kvstore:
      store: memberlist
  processor:
    span_metrics: {}
    service_graphs: {}
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus-${node_id}:9090/api/v1/write
        send_exemplars: true

memberlist:
  join_members:
${tempo_members}
